linters-settings:
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 64
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  # TODO: Revisit after the refactor
  funlen:
    lines: 220
    statements: 120

linters:
  enable-all: true
  disable:
    - depguard
    - ireturn
    - maintidx
    - wrapcheck
    - gci
    - gofumpt
    - nlreturn
    - noctx
    - paralleltest
    - exhaustive
    - exhaustruct
    - tagliatelle
    - unparam
    - err113
    - lll
    - gochecknoinits
    - gochecknoglobals
    - dupl
    - wsl
    - godox
    - gomnd
    # TODO: Revisit after the refactor
    - gocognit
    - nestif